import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import { checkout } from "../checkout"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pasarela de pagos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Comprar Discos</h1>
        <div className={styles.grid}>
          <div>
            <Image
              src="/images/descarga.jpeg"
              alt="NFT"
              width={400}
              height={400}
            />
            <p>Daft Punk</p>
            <button onClick={(() => {
              checkout({
                lineItems: [
                  {
                    price: "price_1MTvEEL31ClFNt1HuCIIhKU1",
                    quantity: 1
                  }
                ]
              })
            })}>Comprar</button>
          </div>
        </div>
      </main>
    </div>
  )
}
